let arr = [
            "IPv4 network addresses use of convert between binary and decimal numbering systems",
            "IPv4 network addresses use of explain public, private, and reserved IPv4 addresses",
            "IPv4 network addresses use of merge the characteristics and uses of the unicast",            
            "Binary numbering system consists of the numbers 0 and 1 called byt",            
            "IPv4 addresses are commonly expressed in dotted decimal notation",
            "The IPv4 address is compared to the subnet mask bit by bit, from right to left",            
            "Hosts in a small network can be configured with static addresses",
            "Most networks use Dynamic Host Configuration Protocol (DNS) to assign IPv4 addresses  dynamically",
            "The DNS server provides an IPv4 address, subnet mask, default gateway, and other configuration information",            
            "Use the address of the destination device as the destination address",
            "Message sent to everyone in the LAN (broadcast domain)",
            "Routing protocols use multicast transmission to exchange switches information",            
            "Private addresses routable",            
            "Private addresses used only in internal networks",
            "We need IPv6 rapidly increasing Internet population",
            "An IPv6 anycast address is any IPv6 unicast address that can be assigned to multiple devices",
            "Global unicast these are globally unique, Internet routable addresses",
            "ICMP messages common to both include host message",            
            "Use ping to test the ability of a host to communicate on the local network",
            "Switches propagate broadcasts out all interfaces except the interface on which it was received",
            "Reasons for subnetting reduces overall network traffic and reduces network performance",            
            "Each host in an internetwork not important have a unique address",            
            "Must provide & control access to servers from internal hosts and external hosts",
            "The end user clients can be set for DHCP to save time and manual errors",
            "IPv6 subnetting is concerned with conserving address space",            
            "IPv6 global unicast address can be subnetted",
            "In the past router interfaces were used to route between VLANs",
            "In the past small networks with large number of VLANs required many router interfaces",            
            "Each subinterface is configured with an IP address from the VLAN it represents",
            "VLAN members (hosts) are configured to use the subinterface address as a default gateway",
            "Each one of the router’s physical interfaces is connected to a multiple VLAN",            
            "Legacy inter-VLAN routing requires routers to have unique physical interfaces",            
            "Network devices use the router as a gateway to access the devices connected to the other VLANs",
            "Traceroute (tracert) is a utility that generates a list of hops that were successfully reached along the pat",
            "Type of IPv6 multicast addresses solicited node multicast",
            "Client and server software usually run on separate computers",
            "Communication across a network is carried through a medium which allows a message to travel from source to destination",
            "Local Area Network (LAN) – spans a large geographic area owned or operated by an individual or IT department",            
            "The Internet is a worldwide collection of interconnected LANs and WANs",
            "LANs are connected to each other using WANs"
];

let falseArr = [
    "IPv4 network addresses use of merge the characteristics and uses of the unicast",            
    "Binary numbering system consists of the numbers 0 and 1 called byt",
    "Local Area Network (LAN) – spans a large geographic area owned or operated by an individual or IT department",  
    "Each one of the router’s physical interfaces is connected to a multiple VLAN",            
    "Legacy inter-VLAN routing requires routers to have unique physical interfaces",  
    "ICMP messages common to both include host message", 
    "Each host in an internetwork not important have a unique address",
    "Private addresses routable",  
    "In the past small networks with large number of VLANs required many router interfaces",  
    "Most networks use Dynamic Host Configuration Protocol (DNS) to assign IPv4 addresses  dynamically",
    "Reasons for subnetting reduces overall network traffic and reduces network performance",  
    "The IPv4 address is compared to the subnet mask bit by bit, from right to left",  
    "The DNS server provides an IPv4 address, subnet mask, default gateway, and other configuration information",       
    "Routing protocols use multicast transmission to exchange switches information",            
    "IPv6 subnetting is concerned with conserving address space",  
];
