// let arrMidOne = [
//             "IPv4 network addresses use of convert between binary and decimal numbering systems",
//             "IPv4 network addresses use of explain public, private, and reserved IPv4 addresses",
//             "IPv4 network addresses use of merge the characteristics and uses of the unicast",            
//             "Binary numbering system consists of the numbers 0 and 1 called byt",            
//             "IPv4 addresses are commonly expressed in dotted decimal notation",
//             "The IPv4 address is compared to the subnet mask bit by bit, from right to left",            
//             "Hosts in a small network can be configured with static addresses",
//             "Most networks use Dynamic Host Configuration Protocol (DNS) to assign IPv4 addresses  dynamically",
//             "The DNS server provides an IPv4 address, subnet mask, default gateway, and other configuration information",            
//             "Use the address of the destination device as the destination address",
//             "Message sent to everyone in the LAN (broadcast domain)",
//             "Routing protocols use multicast transmission to exchange switches information",            
//             "Private addresses routable",            
//             "Private addresses used only in internal networks",
//             "We need IPv6 rapidly increasing Internet population",
//             "An IPv6 anycast address is any IPv6 unicast address that can be assigned to multiple devices",
//             "Global unicast these are globally unique, Internet routable addresses",
//             "ICMP messages common to both include host message",            
//             "Use ping to test the ability of a host to communicate on the local network",
//             "Switches propagate broadcasts out all interfaces except the interface on which it was received",
//             "Reasons for subnetting reduces overall network traffic and reduces network performance",            
//             "Each host in an internetwork not important have a unique address",            
//             "Must provide & control access to servers from internal hosts and external hosts",
//             "The end user clients can be set for DHCP to save time and manual errors",
//             "IPv6 subnetting is concerned with conserving address space",            
//             "IPv6 global unicast address can be subnetted",
//             "In the past router interfaces were used to route between VLANs",
//             "In the past small networks with large number of VLANs required many router interfaces",            
//             "Each subinterface is configured with an IP address from the VLAN it represents",
//             "VLAN members (hosts) are configured to use the subinterface address as a default gateway",
//             "Each one of the router’s physical interfaces is connected to a multiple VLAN",            
//             "Legacy inter-VLAN routing requires routers to have unique physical interfaces",            
//             "Network devices use the router as a gateway to access the devices connected to the other VLANs",
//             "Traceroute (tracert) is a utility that generates a list of hops that were successfully reached along the pat",
//             "Type of IPv6 multicast addresses solicited node multicast",
//             "Client and server software usually run on separate computers",
//             "Communication across a network is carried through a medium which allows a message to travel from source to destination",
//             "Local Area Network (LAN) – spans a large geographic area owned or operated by an individual or IT department",            
//             "The Internet is a worldwide collection of interconnected LANs and WANs",
//             "LANs are connected to each other using WANs"
// ];

// let falseArrMidOne = [
//     "IPv4 network addresses use of merge the characteristics and uses of the unicast",            
//     "Binary numbering system consists of the numbers 0 and 1 called byt",
//     "Local Area Network (LAN) – spans a large geographic area owned or operated by an individual or IT department",  
//     "Each one of the router’s physical interfaces is connected to a multiple VLAN",            
//     "Legacy inter-VLAN routing requires routers to have unique physical interfaces",  
//     "ICMP messages common to both include host message", 
//     "Each host in an internetwork not important have a unique address",
//     "Private addresses routable",  
//     "In the past small networks with large number of VLANs required many router interfaces",  
//     "Most networks use Dynamic Host Configuration Protocol (DNS) to assign IPv4 addresses  dynamically",
//     "Reasons for subnetting reduces overall network traffic and reduces network performance",  
//     "The IPv4 address is compared to the subnet mask bit by bit, from right to left",  
//     "The DNS server provides an IPv4 address, subnet mask, default gateway, and other configuration information",       
//     "Routing protocols use multicast transmission to exchange switches information",            
//     "IPv6 subnetting is concerned with conserving address space",  
// ];

let arr = [
"A router learns about remote networks in three ways",
"A router learns about remote networks dynamically (Automatically) learned using a routing protocol", 
"Use static routes to connect to a public network", 
"Use static Routes to connect a stub router", 
"Use static routes to Create a backup route in case a primary route link fails", 
"Default route matches all packets and is used when a packet match a specific route in the routing table", 
"Can be dynamically learned or statically configured", 
"Default static route creates a gateway of last resort", 
"Default static route Common use is when connecting a company’s edge router to the ISP network", 
"Router has multi routers to which it is connected", 
"Destination networks does not must be contiguous", 
"Multiple static routes destination networks does not must be contiguous multiple static routes", 
"Floating static route used when primary route is not available", 
"Default route is used when no other routes in the routing table match the destination IP", 
"RIP protocol was updated to RIPv2 to accommodate growth in the network environment", 
"Routing Protocols developed to meet the need of small networks include OSPF", 
"Routing protocols developed to meet the need of small networks include Enhanced IGRP (EIGRP)", 
"Border Gateway Protocol (BGP) is used between Internet service providers (ISPs)", 
"Purpose of dynamic routing protocols includes discovery of only connect networks", 
"Purpose of dynamic routing protocols includes ability to find a new best path if the current path is no longer available", 
"Purpose of dynamic routing protocols includes maintaining old data routeing information", 
"Purpose of dynamic routing protocols includes choosing the best path to destination networks", 
"The main components of dynamic routing protocols include data structures - tables or databases kept in Flash", 
"The main components of dynamic routing protocols include algorithms – to facilitate learning routing information and for best path determination", 
"Networks never use both static and dynamic routing", 
"Static routing is used for easy routing table maintenance in small networks", 
"Static routing is used routing to and from a stub network", 
"Static routing is used to accessing a multi default route", 
"Dynamic routing is the best choice for large networks", 
"Dynamic routing protocols help the network administrator manage the network Providing redundant paths", 
"Entries contain the following information route destination", 
"Entries contain the following destination network", 
"The routing table is a hierarchical structure that is used to speed up the lookup process when locating routes and forwarding packets", 
"An ultimate route is a routing table entry that contains either a next-hop IPv4 address or an exit interface", 
"Network route a network route that has a subnet mask equal to that of the classful mask", 
"Supernet route a network address with a mask less than the classful mask, for example, a summary address", 
"Default route - a static route with the address 0.0.0.0/0", 
"In the routing table, it basically provides a heading for the public subnets it contains", 
"Router lookup process If the best match is a level 1 ultimate route, then this route is used to forward the packet", 
"The route with the greatest number of equivalent near left bits, or the longest match, is always the preferred route", 
"All IPv6 routes are level 1 ultimate routes"];

let falseArr = [
"A router learns about remote networks in three ways",
"Use static routes to connect to a public network",
"Default route matches all packets and is used when a packet match a specific route in the routing table",
"Router has multi routers to which it is connected",
"Destination networks does not must be contiguous", 
"Multiple static routes destination networks does not must be contiguous multiple static routes", 
"Routing Protocols developed to meet the need of small networks include OSPF", 
"Routing protocols developed to meet the need of small networks include Enhanced IGRP (EIGRP)", 
"Purpose of dynamic routing protocols includes discovery of only connect networks",
"Purpose of dynamic routing protocols includes maintaining old data routeing information", 
"The main components of dynamic routing protocols include data structures - tables or databases kept in Flash", 
"Networks never use both static and dynamic routing", 
"Static routing is used to accessing a multi default route", 
"Entries contain the following information route destination", 
"In the routing table, it basically provides a heading for the public subnets it contains", 
"The route with the greatest number of equivalent near left bits, or the longest match, is always the preferred route", 
];
